spring:
  profiles:
    active: test
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: course-service-student-request-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        # OU
        # spring.json.value.default.type: com.seu.pacote.SuaClasseDTO
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    topic:
      request-course-from-student: request-list-available-courses