spring:
  config:
    activate:
      on-profile: dev

postgres:
  username: postgres
  password: 123
  database: custom_grant

logging:
  level:
    org.springframework.security: DEBUG
    orr.springframework.security.oauth2=DEBUG:

