spring:
  profiles:
    active: test

  jpa:
    open-in-view: false

security:
  client:
    client-id: ${CLIENT_ID:default-client-id}
    client-secret: ${CLIENT_SECRET:default-secret}
    redirect-uris: ${REDIRECT_URI:http://localhost:8080/login/oauth2/code/my-client-id}
  jwt:
    duration: ${JWT_TOKEN_DURATION:86400}
