server:
  port: 8082
spring:
  profiles:
    active: test
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id:
        student-course-response: student-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.customgrant.student_service.dto"
        # OU
        # spring.json.value.default.type: com.seu.pacote.SuaClasseDTO
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      response-course-available-courses: response-list-available-courses
      request-course-available-courses: request-list-available-courses