services:
  db:
    image: bitnami/postgresql:17.4.0
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: authentication-service
      POSTGRESQL_POSTGRESQL_CONF_FILE: /opt/bitnami/postgresql/conf/postgresql.conf
      POSTGRESQL_EXTRA_FLAGS: "-c wal_level=logical -c max_wal_senders=4 -c max_replication_slots=4"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - shared_net
volumes:
  postgres_data:
networks:
  shared_net:
    driver: bridge
