services:
  db:
    image: bitnami/postgresql:17.4.0
    container_name: postgres_db-course
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: course-service
      POSTGRESQL_EXTRA_FLAGS: "-c wal_level=logical -c max_wal_senders=4 -c max_replication_slots=4"
    ports:
      - "5434:5434"
    volumes:
      - postgres_data_course:/var/lib/postgresql/data
    networks:
      - shared_net_course

networks:
  shared_net_course:

volumes:
  postgres_data_course:
