services:
  db:
    image: bitnami/postgresql:17.4.0
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: custom_grant
      POSTGRESQL_EXTRA_FLAGS: "-c wal_level=logical -c max_wal_senders=4 -c max_replication_slots=4"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_student:/var/lib/postgresql/data
    networks:
      - shared_net_student

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka-kraft
    hostname: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://kafka:29093,CONTROLLER://kafka:29094,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_JMX_PORT: 9102
      KAFKA_JMX_HOSTNAME: kafka-kraft
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_HOST
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: 329bd443-a747-453b-82ea-96910b808d62
    ports:
      - "9093:9093"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - shared_net_student

  kafka-connect:
    image: confluentinc/cp-kafka-connect-base:7.9.0
    container_name: kafka-connect
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:29093"
      CONNECT_REST_PORT: 8084
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-config
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflection=ERROR"
      CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: /kafka/connect
    ports:
      - "8084:8084"
    networks:
      - shared_net_student
    depends_on:
      - kafka
    volumes:
      - kafka_connect:/kafka/connect

networks:
  shared_net_student:

volumes:
  kafka_data:
  kafka_connect:
  postgres_data_student:
